export const SET_SEARCH_PLACES_TYPE = 'SET_SEARCH_PLACES_TYPE';

export const SET_MY_PLACES = 'SET_MY_PLACES';

export const LOGIN_START = 'LOGIN_START';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_FAILURE = 'LOGIN_FAILURE';
export const LOG_OUT = 'LOG_OUT';